name: Hello World
on: [push]
jobs:
  HelloWorld: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch helloworld.cpp
      - run: g++ helloworld.cpp
      - run: ./a.out